apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: workshop-keycloakrealm
  labels:
    app: sso
spec:
  realm:
    id: "c55c6f57-cc91-464c-b9be-119cdf1aac3f"
    realm: "workshop"
    enabled: True
    displayName: "Workshop"
    roles:
    - id: b63e2bff-d9bf-4f94-bde9-c097d9e0a531
      name: library_curator
      description: Library curator
      composite: false
      clientRole: false
      containerId: c55c6f57-cc91-464c-b9be-119cdf1aac3f
      attributes: {}
    - id: 8b61bbdb-913a-4874-b385-09b357c022ae
      name: uma_authorization
      description: "${role_uma_authorization}"
      composite: false
      clientRole: false
      containerId: c55c6f57-cc91-464c-b9be-119cdf1aac3f
      attributes: {}
  instanceSelector:
    matchLabels:
      app: sso